### PR TITLE
Update Fork

### PR DESCRIPTION
**Pull request by DK101010**
## Types of changes

- [] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Enhancement (improves an existing feature and functionality)
- [ ] Cleanup (Code refactoring and cleanup, that may add test cases)

### CODE REVIEW

**Comment by DaanHoogland** [comment]
@DK101010 , 
image

I think you will want to get master from origin and force push it here. define or redefine origin as the apache cloudstack repo and define yours as "mine" or "dk" or something. makes sense?

**Comment by DK101010** [comment]
Hi Dahn,
at first, I have forked the apache/cloudstack into my projects via GitHub,
after this I cloned my forked repository. Last month, I merged
apache/cloudstack master into my fork via GitHub with a pull request.
Then we talked together about it yesterday and you means that is not so
good.
For this reason I've added the apache/cloudstack into my remote repository
mit git remote add ... and pulled into my forked master

Now I want to find out if this correct, the result can you see here (
https://github.com/apache/cloudstack/pull/4548)
[image: image.png]

 it this a better solution?

The only one that I know  to prevent a merge commit is to use rebase, but a
rebase of apache master to my forked master sounds not pretty well.

Many Greetings
Dirk


Am Mi., 16. Dez. 2020 um 13:07 Uhr schrieb dahn <notifications@github.com>:

**Comment by DaanHoogland** [comment]
so what are the output of `git remote -v`, and `git branch -v`?

**Comment by DK101010** [comment]
[image: image.png]

Am Mi., 16. Dez. 2020 um 16:00 Uhr schrieb dahn <notifications@github.com>:

**Comment by DaanHoogland** [comment]
> [image: image.png]

is not the text i was looking for :D

**Comment by DaanHoogland** [comment]
better not use github with mail. it doesn't work that well

**Comment by DK101010** [comment]
sorry :D 
next try
image

**Comment by DaanHoogland** [comment]
Ah I should have said `git branch -vv`
an snippet from my output:
```
* marvin3                  3e228ea390 [sb/marvin3] env run of python3
  master                   58a0a7b1a3 [origin/master] Merge remote-tracking branch 'origin/4.14'
```
it shows how `master` is from `origin` (tracking `origin/master`) and `marvin3` in on my company account (alias `sb`). `marvin3` was a fork of master but pushed to a different account. next I created a pull request on github from `shapeblue:marvin3` to `apache:master` and if i kept my local `master` up to date all is dandy and fine.
Your master is showing 78 ahead, that can't be good. I would sugest:
```
git branch -D master
git checkout -b master apache/master
```
the first line is destructive! I would also not name your own origin but something like mine or DK or so.

**Comment by DK101010** [comment]
Ahh ok, I understand what you want and approved my assumption. My master should pointed to the apache/cloudstack master and not to my forked master. I will remove my master add the apache/cloudstack master, clean up my newest branch, merge the new master in this branch and then should be the problem solved. 

I let you know when I pushed my updated branch, ok? 

Many thanks for your support :)

**Comment by DK101010** [comment]
@DaanHoogland Now looks good https://github.com/apache/cloudstack/pull/4548/commits

**Comment by DaanHoogland** [comment]
yes, it does

**Pull request merged**
